---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: app
  namespace: app
spec:
  http:
    - name: lambda
      labels:
        route: lambda
      forwardTo:
        destinations:
          - ref:
              name: aws-provider
              namespace: devops
              cluster: mgmt
            kind: CLOUD_PROVIDER
            function:
              logicalName: gloo-platform-lambda-demo-latest
              awsLambda:
                unwrapAsApiGateway: true
    
