---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: app
  namespace: gloo-mesh
spec:
  workloadClusters:
    - name: '*'
      namespaces:
        - name: app
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: app
  namespace: app
spec:
  importFrom:              
  - workspaces:
    - name: 'devops'
    - name: 'gateway'
  exportTo:
  - workspaces:
    - name: 'gateway'
