apiVersion: networking.gloo.solo.io/v2
kind: CloudResources
metadata:
  name: aws-resources
  namespace: default
spec:
  provider: aws-provider
  lambda:
    - logicalName: gloo-platform-lambda-demo-latest
      lambdaFunctionName: gloo-platform-lambda-demo
      qualifier: $LATEST
    - logicalName: golang-apigw-latest
      lambdaFunctionName: golang-apigw-latest
      qualifier: $LATEST


    