apiVersion: networking.gloo.solo.io/v2
kind: CloudProvider
metadata:
  name: aws-provider
  namespace: devops
spec:
  aws:
    stsEndpoint: sts.amazonaws.com
    accountId: "000000000000"
    region: us-west-1
    lambda:
      invokeRoleName: gloo-platform-lambda-demo-invoke
