---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gateway
  namespace: istio-gateways
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: lambda-demo-north-south-gw
      namespace: istio-gateways
      cluster: mgmt
  http:
    - name: sanity
      matchers:
        - uri:
            prefix: /sanity
      labels:
        route: sanity
      directResponse:
        status: 200
        body: "it's alive"
    - name: lambda
      matchers:
      - uri:
          prefix: /lambda
      delegate:
        routeTables:
        - workspace: app
        allowedRoutes:
          cloudProvider:
            aws:
              iamRoles:
              # allow a specific role
              - gloo-lambda-executor
              # allow any role
              - ".*"