apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloud-provider.yaml
- cloud-resources.yaml
- virtual-gateway.yaml
- gateway-workspace.yaml
- gateway-routetable.yaml
- app-workspace.yaml
- app-routetable.yaml
- devops-workspace.yaml