apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: lambda-demo-north-south-gw
  namespace: istio-gateways
spec:
  listeners:
    - http: {}
      port:
        number: 80
  workloads:
    - selector:
        cluster: mgmt
        labels:
          istio: ingressgateway