apiVersion: networking.gloo.solo.io/v2
kind: CloudProvider
metadata:
  name: aws-provider
  namespace: default
spec:
  aws:
    accountId: "000000000000"
    region: us-east-1
    lambda:
      invokeRoleName: gloo-lambda-executor
